### ISSUE TITLE
missing positional arguments: 'latitude' and 'longitude'

### ISSUE THREAD

**Issue by Konsebast** [oemof/feedinlib#22] opened 2016-08-23 07:35 UTC
Hello,

I am working atm with the feedinlib. The creation of the feedin of a wind power geenrator worked very well. Now I am struggeling with the pv module.

If I just use the example file, I get the following Error:

```python
PS D:\OneDrive\Desktop\feedinlib-dev(1)\feedinlib-dev\example> python feedinlib_example.py
INFO:root:Copying weather data from http://vernetzen.uni-flensburg.de/~git/weather.csv to C:\Users\Konstantin Kubina\.oe
mof\weather.csv
INFO:root:Copying weather data from http://vernetzen.uni-flensburg.de/~git/weather_wittenberg.csv to C:\Users\Konstantin
 Kubina\.oemof\weather_wittenberg.csv
C:\Users\Konstantin Kubina\.oemof\weather.csv
C:\Users\Konstantin Kubina\.oemof\weather_wittenberg.csv
INFO:root:Failed loading cp values from hdf file, trying csv.
INFO:root:Failed loading cp values from hdf file, trying csv.
Traceback (most recent call last):
  File "feedinlib_example.py", line 141, in <module>
    pv_feedin1 = yingli_module.feedin(weather=my_weather, number=30000)
  File "C:\Python34\lib\site-packages\feedinlib\powerplants.py", line 146, in feedin
    return super().feedin(**kwargs)
  File "C:\Python34\lib\site-packages\feedinlib\powerplants.py", line 112, in feedin
    feedin = self.model.feedin(**combined) * kwargs['number']
  File "C:\Python34\lib\site-packages\feedinlib\models.py", line 132, in feedin
    return self.get_pv_power_output(**kwargs).p_mp
  File "C:\Python34\lib\site-packages\feedinlib\models.py", line 510, in get_pv_power_output
    data = self.solarposition_hourly_mean(location, data, **kwargs)
  File "C:\Python34\lib\site-packages\feedinlib\models.py", line 178, in solarposition_hourly_mean
    time=data_5min.index, location=location, method='ephemeris')
TypeError: get_solarposition() missing 2 required positional arguments: 'latitude' and 'longitude'
```

Here is the Example File:
```python
#!/usr/bin/python3
# -*- coding: utf-8

import pandas as pd
import logging
import os
try:
    from urllib.request import urlretrieve
except:
    from urllib import urlretrieve

try:
    from matplotlib import pyplot as plt
    plot_fkt = True
except:
    plot_fkt = False

from feedinlib import powerplants as plants
from feedinlib import models
from feedinlib import weather

# Feel free to remove or change these lines
import warnings
warnings.simplefilter(action="ignore", category=RuntimeWarning)
logging.getLogger().setLevel(logging.INFO)


# Specification of the weather data set CoastDat2
coastDat2 = {
    'dhi': 0,
    'dirhi': 0,
    'pressure': 0,
    'temp_air': 2,
    'v_wind': 10,
    'Z0': 0}

# Specification of the pv module
advent210 = {
    'module_name': 'Advent_Solar_Ventura_210___2008_',
    'azimuth': 180,
    'tilt': 30,
    'albedo': 0.2}

# Specification of the pv module
yingli210 = {
    'module_name': 'Yingli_YL210__2008__E__',
    'azimuth': 180,
    'tilt': 30,
    'albedo': 0.2}

# Specifications of the wind turbines
enerconE126 = {
    'h_hub': 135,
    'd_rotor': 127,
    'wind_conv_type': 'ENERCON E 126 7500'}

vestasV90 = {
    'h_hub': 105,
    'd_rotor': 90,
    'wind_conv_type': 'VESTAS V 90 3000'}


def download_file(filename, url):
    if not os.path.isfile(filename):
        logging.info('Copying weather data from {0} to {1}'.format(
            url, filename))
        urlretrieve(url, filename)


def fetch_example_files():
    basic_path = os.path.join(os.path.expanduser("~"), '.oemof')
    filename1 = os.path.join(basic_path, 'weather.csv')
    url1 = 'http://vernetzen.uni-flensburg.de/~git/weather.csv'
    filename2 = os.path.join(basic_path, 'weather_wittenberg.csv')
    url2 = 'http://vernetzen.uni-flensburg.de/~git/weather_wittenberg.csv'
    if not os.path.exists(basic_path):
        os.makedirs(basic_path)
    download_file(filename1, url1)
    download_file(filename2, url2)
    return filename1, filename2


def ready_example_data(filename, datetime_column='Unnamed: 0'):
    df = pd.read_csv(filename)
    return df.set_index(pd.to_datetime(df[datetime_column])).tz_localize(
        'UTC').tz_convert('Europe/Berlin').drop(datetime_column, 1)


filename1, filename2 = fetch_example_files()
print(filename1)
print(filename2)
# Two Variants to create your weather object
# 1. Variant: Passing all data to the weather class
weather_df = ready_example_data(filename1)
my_weather_a = weather.FeedinWeather(
    data=weather_df,
    timezone='Europe/Berlin',
    latitude=52,
    longitude=13,
    data_height=coastDat2)

# 2. Variant: Loading a csv-file that has the feedinlib-csv-header (see docs)
my_weather_b = weather.FeedinWeather()
my_weather_b.read_feedinlib_csv(filename=filename2)

# Loading the weather data
my_weather = my_weather_b

# Initialise different power plants
# So far there is only one model available. So you do not have to pass a model
# (s. E126). If model is passed the default model is used.
# We hope that there will be different models in future versions. You can also
# write your own model an pass it to the powerplant.
E126_power_plant = plants.WindPowerPlant(**enerconE126)
V90_power_plant = plants.WindPowerPlant(model=models.SimpleWindTurbine,
                                        **vestasV90)

# Create a feedin series for a specific powerplant under specific weather
# conditions. One can define the number of turbines or the over all capacity.
# If no multiplier is set, the time series will be for one turbine.
E126_feedin = E126_power_plant.feedin(weather=my_weather, number=2)
V90_feedin = V90_power_plant.feedin(weather=my_weather,
                                    installed_capacity=15 * 10 ** 6)

E126_feedin.name = 'E126'
V90_feedin.name = 'V90'

if plot_fkt:
    E126_feedin.plot(legend=True)
    V90_feedin.plot(legend=True)
    plt.show()
else:
    print(V90_feedin)

# Initialise different power plants
# If you do not pass a model the default model is used. So far there is only
# one model available. This might change in future versions.
yingli_module = plants.Photovoltaic(**yingli210)
advent_module = plants.Photovoltaic(model=models.PvlibBased, **advent210)

pv_feedin1 = yingli_module.feedin(weather=my_weather, number=30000)
pv_feedin2 = yingli_module.feedin(weather=my_weather, area=15000)
pv_feedin3 = yingli_module.feedin(weather=my_weather, peak_power=15000)
pv_feedin4 = yingli_module.feedin(weather=my_weather)
pv_feedin5 = advent_module.feedin(weather=my_weather)

pv_feedin4.name = 'Yingli'
pv_feedin5.name = 'Advent'

# Output
if plot_fkt:
    pv_feedin4.plot(legend=True)
    pv_feedin5.plot(legend=True)
    plt.show()
else:
    print(pv_feedin5)

# Use directly methods of the model
# Write out all possible wind turbines.
w_model = models.SimpleWindTurbine()
w_model.get_wind_pp_types()

# Write out all possible pv-converters
print(models.PvlibBased().fetch_module_data(
    module_name='all', lib='sandia-modules').keys())

# Plot the cp curve of a wind turbine.
cp_values = models.SimpleWindTurbine().fetch_cp_values(
    wind_conv_type='ENERCON E 126 7500')
if plot_fkt:
    plt.plot(cp_values.loc[0, :][2:55].index,
             cp_values.loc[0, :][2:55].values, '*')
    plt.show()
else:
    # The value for 8 m/s
    index = cp_values.loc[0, :][2:55].index == '8'
    print(cp_values.loc[0, :][2:55].values[index][0])

logging.info('Done!')
```

The Positional Arguments should normally be in here (weather_wittenberg.csv):
```python
# name: Wittenberg/Germany
# longitude: 13
# latitude: 52 
# timezone: Europe/Berlin
# data_height temp_air: 2
# data_height v_wind: 10
```

I can not figure out, why the positional arguments are not transferred to the pvlib.

Thank you for your help.

**Comment by uvchik** [comment] 2016-08-23 12:14
Thank you, for your report. The error was caused by a change of the pvlib API. I fixed it with version 0.0.9. Use this version `pip3 install feedinlib --upgrade` or fetch the actual master branch.

Please close this issue, if everything works fine.

**Closed** 2016-08-24 08:23 UTC
Labels: bug
